name: firecrawl
services:
  # Deep Conversational Swarm Research
  # dcsr:
  #   build: .
  #   image: deep-conversational-research:latest
  #   container_name: dcsr.local
  #   ports:
  #     - 3210:3210
  #   environment:
  #     - PORT=3210
  #     - FIRECRAWL_URL=http://firecrawl-api:3002
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - OPENAI_API_URL=${OPENAI_API_URL}
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_DB=${POSTGRES_DB:-deep_conversational_research}
  #     - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
  #     - POSTGRES_PORT=${POSTGRES_PORT:-5432}
  #   links:
  #     - firecrawl-api
  #     - postgres
  #   networks:
  #     - dcsr-net
  #   volumes:
  #     - dcsr-data:/app/logs

  # Firecrawl services
  playwright-service:
    image: trieve/puppeteer-service-ts:v0.0.6
    container_name: playwright-service.local
    environment:
      - PORT=3000
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - BLOCK_MEDIA=${BLOCK_MEDIA}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
      - TWOCAPTCHA_TOKEN=${TWOCAPTCHA_TOKEN}
    networks:
      - dcsr-net

  firecrawl-api:
    image: trieve/firecrawl:v0.0.46
    container_name: playwright-api.local
    networks:
      - dcsr-net
    environment:
      - REDIS_URL=${FIRECRAWL_REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${FIRECRAWL_REDIS_URL:-redis://redis:6379}
      - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - PORT=${PORT:-3002}
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - HOST=${HOST:-0.0.0.0}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - MAX_RAM=${MAX_RAM:-0.95}
      - MAX_CPU=${MAX_CPU:-0.95}
      - COREPACK_DEFAULT_TO_LATEST=0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - playwright-service
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start:production"]

  firecrawl-worker:
    image: trieve/firecrawl:v0.0.46
    container_name: firecrawl-worker.local
    networks:
      - dcsr-net
    environment:
      - REDIS_URL=${FIRECRAWL_REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${FIRECRAWL_REDIS_URL:-redis://redis:6379}
      - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - PORT=${PORT:-3002}
      - NUM_WORKERS_PER_QUEUE=${NUM_WORKERS_PER_QUEUE}
      - BULL_AUTH_KEY=${BULL_AUTH_KEY}
      - TEST_API_KEY=${TEST_API_KEY}
      - SCRAPING_BEE_API_KEY=${SCRAPING_BEE_API_KEY}
      - HOST=${HOST:-0.0.0.0}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - MAX_RAM=${MAX_RAM:-0.95}
      - MAX_CPU=${MAX_CPU:-0.95}
      - COREPACK_DEFAULT_TO_LATEST=0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - playwright-service
      - firecrawl-api
    command: ["pnpm", "run", "workers"]

  redis:
    image: redis:alpine
    networks:
      - dcsr-net
    command: redis-server --bind 0.0.0.0

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-deep_conversational_research}
    ports:
      - "65432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dcsr-net
    expose:
      - "65432"

networks:
  dcsr-net:
    driver: bridge

volumes:
  dcsr-data:
    driver: local
  postgres-data:
    driver: local
